### ISSUE TITLE
Signing modal biometrics key buggy

### ISSUE THREAD

**Issue by HERRKIN** [obi-wallet/obi-wallet#107]
when setting the biometrics key for the first time the app will take longer so it makes me think the process failed and I keep pressing on it. 

maybe it needs some loading screen?

**Comment by BlockJayn** [comment]
I'll have a look at it after finishing with my current task 👍

**Comment by BlockJayn** [comment]
@HERRKIN Somehow I cannot reproduce the issue (as I couldnt find anything that seems to cause a loading-time), but I've added a "disable button onPress" to prevent a doubeclick. I think the current loading-component (it's a full-screen-loader) wouldnt be suitable on this screen, as it would pop-up just for a few milliseconds in many cases. That would probably cause a more "buggy look" for the user. Maybe the `<Button>` itself should be extended with a small loading-icon-feature at the right side of the button-text. I'll keep that in mind.

[Current Pull Request for this topic](https://github.com/obi-wallet/obi-wallet/pull/113)

**Comment by BlockJayn** [comment]
Okay, now I know what you mean @HERRKIN , just happened to me too (as you said, happens on first time starting the app clean). some small loading indicator definitely makes sense here.

**Comment by inyono** [comment]
This has been addresses AFAIK. Feel free to reopen if you think there's still something to do.
