### ISSUE TITLE
Tabbar needs more bottom padding

### ISSUE THREAD

**Issue by inyono** [obi-wallet/obi-wallet#90]
"home screen button" is over the icons:

![IMG_F970CAE5A848-1](https://user-images.githubusercontent.com/1508477/189124030-2aa3e9e2-64bc-4d8a-b382-e24aff377c60.jpeg)

**Comment by BlockJayn** [comment]
ahh good to know, looked fine on iPhone 13 Pro Max.
I should add a 3rd Simulator to make sure everything is looking good
(Smallest Device with modified sizes) + (Standard Screen Size in smallest and biggest screen view)

I'll fix that!

**Comment by BlockJayn** [comment]
Fixed. Will be part of my next PR for all the fixes

<img width="759" alt="Screenshot 2022-09-09 at 00 58 15" src="https://user-images.githubusercontent.com/99530800/189240300-aae807aa-3300-46c9-96ee-2794839628ef.png">

**Comment by inyono** [comment]
Please don't close issues if the fixes aren't in master yet. You can add `Close #90` to your commit message or PR body so that GitHub automatically closes this issue if that commit / PR is merged into master.
